### ISSUE TITLE
Devrimci Karargah, DKP/BÖG şıkları aynı anda oluşturulmamalı

### ISSUE THREAD

**Issue by kapozade** [osumatu/terorist-quiz#18]
Devrimci Karargah, DKP/BÖG ile birleştiğinden dolayı şık üretiminde iki şık beraber yer almamalı.

**Comment by ulughann** [comment]
neden bu konuda bu kadar bilgin var bilemiyorum ama halletim 👍
#23

**Comment by kapozade** [comment]
Teröristini doğru tanı Türkiye motto değil mi :)

**Comment by osumatu** [comment]
Selamlar, bilgi dogru olabilir ancak bu repo kapsaminda veri manuplasyonuna girmek hic istemiyorum acikcasi. Gelen veriyi hic yorumlamadan gostermek daha guvenli geliyor. Onlari birlestirelim, bunlari cikaralim durumuna girdigimizde verinin gorece sahibi hale geliyoruz ve sorumluluk yuklenebilir gibime geliyor.

**Comment by kapozade** [comment]
Hmm, bu açıdan düşününce doğru ve yerinde bir yaklaşım 👍🏿  Teşekkürler.
