### ISSUE TITLE
Mitte işe çağırıldım fakat başvuru linki vermedi.

### ISSUE THREAD

**Issue by zog06** [osumatu/terorist-quiz#8]
Mit başvuru linki eklemeyi unutmuşsunuz hocam. 
Badem bıyıklıları iyi tespit ettiğim için MIT göreve çağırdı ama link yok.

İşin şakası elinize sağlık.

**Comment by memuremeklisi** [comment]
yeni ekledim bakalım https://github.com/osumatu/terorist-quiz/compare/main...memuremeklisi:terorist-quiz:main
