### ISSUE TITLE
Hatalı Veri Seti

### ISSUE THREAD

**Issue by cemahseri** [osumatu/terorist-quiz#9]
Sanıyorum ki verileri https://terorarananlar.pol.tr/ hizmetinden topladınız. Veriler büyük oranda doğru olsa da bazen aile yakınlarım çıkıyor. Bazen "Sivil" seçeneği çıkmıyor. "Sivil" seçeneği varken onu seçsem bile doğru cevabın "FETÖ/PDY" olduğunu söylüyor. Bunu düzeltebilirseniz sevinirim.

**Comment by erdemhglu** [comment]
Sanırım aileniz hakkında bilmediğiniz şeyler var...
